src/Entity/Experiment.php
<?php
//    datenbank-physik
//    Copyright (C) 2020  Christian Seybert, Jan-Philipp Rogge, Jacob Benz, Alexander Hartmann, Sarah Schirmacher
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published
//    by the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ExperimentRepository")
 * @Vich\Uploadable
 */
class Experiment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $preparationTime;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="experiments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Document", mappedBy="experiment", cascade={"persist", "remove"})
     */
    private $documents;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="experiment", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string")
     */
    private $status;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Label", inversedBy="experiments", cascade={"persist"})
     */
    private $labels;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $execution_time;

    /**
     * @ORM\Column(type="json_array", nullable=true)
     */
    private $safety_signs = [];

    /**
     * @ORM\Column(type="integer")
     */
    private $experimentNumber;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commit", mappedBy="experiment", orphanRemoval=true)
     */
    private $commits;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ReservationExperiment", mappedBy="experiment", orphanRemoval=true)
     */
    private $reservationExperiments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->labels = new ArrayCollection();
        $this->commits = new ArrayCollection();
        $this->reservationExperiments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getPreparationTime(): ?int
    {
        return $this->preparationTime;
    }

    public function setPreparationTime(?int $preparationTime): self
    {
        $this->preparationTime = $preparationTime;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $documents): self
    {
        if (!$this->documents->contains($documents)) {
            $this->documents[] = $documents;
            $documents->setExperiment($this);
        }

        return $this;
    }

    public function removeDocument(Document $documents): self
    {
        if ($this->documents->contains($documents)) {
            $this->documents->removeElement($documents);
            // set the owning side to null (unless already changed)
            if ($documents->getExperiment() === $this) {
                $documents->setExperiment(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setExperiment($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getExperiment() === $this) {
                $comment->setExperiment(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|Label[]
     */
    public function getLabels(): Collection
    {
        return $this->labels;
    }

    public function addLabel(Label $label): self
    {
        if (!$this->labels->contains($label)) {
            $this->labels[] = $label;
        }

        return $this;
    }

    public function removeLabel(Label $label): self
    {
        if ($this->labels->contains($label)) {
            $this->labels->removeElement($label);
        }

        return $this;
    }

    public function getExecutionTime(): ?int
    {
        return $this->execution_time;
    }

    public function setExecutionTime(?int $execution_time): self
    {
        $this->execution_time = $execution_time;

        return $this;
    }

    public function getSafetySigns(): ?array
    {
        return $this->safety_signs;
    }

    public function setSafetySigns(?array $safety_signs): self
    {
        $this->safety_signs = $safety_signs;

        return $this;
    }

    public function getExperimentNumber(): ?int
    {
        return $this->experimentNumber;
    }

    public function setExperimentNumber(int $experimentNumber): self
    {
        $this->experimentNumber = $experimentNumber;

        return $this;
    }

    /**
     * @return Collection|Commit[]
     */
    public function getCommits(): Collection
    {
        return $this->commits;
    }

    public function addCommit(Commit $commit): self
    {
        if (!$this->commits->contains($commit)) {
            $this->commits[] = $commit;
            $commit->setExperiment($this);
        }

        return $this;
    }

    public function removeCommit(Commit $commit): self
    {
        if ($this->commits->contains($commit)) {
            $this->commits->removeElement($commit);
            // set the owning side to null (unless already changed)
            if ($commit->getExperiment() === $this) {
                $commit->setExperiment(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ReservationExperiment[]
     */
    public function getReservationExperiments(): Collection
    {
        return $this->reservationExperiments;
    }

    public function addReservationExperiment(ReservationExperiment $reservationExperiment): self
    {
        if (!$this->reservationExperiments->contains($reservationExperiment)) {
            $this->reservationExperiments[] = $reservationExperiment;
            $reservationExperiment->setExperiment($this);
        }

        return $this;
    }

    public function removeReservationExperiment(ReservationExperiment $reservationExperiment): self
    {
        if ($this->reservationExperiments->contains($reservationExperiment)) {
            $this->reservationExperiments->removeElement($reservationExperiment);
            // set the owning side to null (unless already changed)
            if ($reservationExperiment->getExperiment() === $this) {
                $reservationExperiment->setExperiment(null);
            }
        }

        return $this;
    }
}

src/Form/ExperimentType.php
<?php
//    datenbank-physik
//    Copyright (C) 2020  Christian Seybert, Jan-Philipp Rogge, Jacob Benz, Alexander Hartmann, Sarah Schirmacher
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published
//    by the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

namespace App\Form;

use App\Entity\Category;
use App\Entity\Experiment;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ExperimentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description', TextareaType::class, [
                'required' => false
            ])
            ->add('comment', TextareaType::class, [
                'required' => false
            ])
            ->add('preparationTime')
            ->add('execution_time')
            ->add('status', ChoiceType::class, [
                'choices'  => [
                    'Verfügbar' => 'available',
                    'Nicht Verfügbar' => 'notavailable',
                    'Entwurf' => 'draft'
                ],
                'data' => $options['choice'],
            ])
            ->add('safety_signs', SignSelectorType::class, [
                'label' => 'Sicherheitszeichen',
                'multiple' => true,
                'expanded' => true,
                'choices'  => [
                    'W001' => 'W001',
                    'W002' => 'W002',
                    'W003' => 'W003',
                    'W004' => 'W004',
                    'W005' => 'W005',
                    'W006' => 'W006',
                    'W009' => 'W009',
                    'W010' => 'W010',
                    'W012' => 'W012',
                    'W016' => 'W016',
                    'W017' => 'W017',
                    'W021' => 'W021',
                    'W022' => 'W022',
                    'W023' => 'W023',
                    'W027' => 'W027',
                    'W028' => 'W028',
                    'W029' => 'W029',
                    'M001' => 'M001',
                    'M003' => 'M003',
                    'M004' => 'M004',
                    'M005' => 'M005',
                    'M007' => 'M007',
                    'M008' => 'M008',
                    'M009' => 'M009',
                    'M011' => 'M011',
                    'M013' => 'M013',
                    'M017' => 'M017',
                    'M026' => 'M026',
                ],
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => function ($category) {
                    return $category->getToken(). ': ' .$category->getName();
                },
                'choice_value' => 'id',
                'choices' => $options['availableCategories'],
                'group_by' => function ($value, $key, $index) {
                    return mb_substr($value->getToken(), 0, 1);
                },
            ])
            ->add('experimentNumber')
            ->add('labels', TagifyType::class, [
                'label' => 'Gerätelabels'
            ])
            ->add('documents', CollectionType::class, [
                'entry_type' => DocumentType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'attr' => [
                    'data-entry-label' => 'Document'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Experiment::class,
            'availableCategories' => Category::class,
            'choice' => 'draft'
        ]);
    }
}

templates/experiment/view/comments.html.twig
{#  datenbank-physik
    Copyright (C) 2020  Christian Seybert, Jan-Philipp Rogge, Jacob Benz, Alexander Hartmann, Sarah Schirmacher
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>. #}

{% extends 'experiment/view.html.twig' %}
{% block content %}
    <div id="comments">
        {% include 'experiment/view/comment/base.html.twig' %}
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('comment') }}
{% endblock %}

templates/experiment/view/commits.html.twig
{#  datenbank-physik
    Copyright (C) 2020  Christian Seybert, Jan-Philipp Rogge, Jacob Benz, Alexander Hartmann, Sarah Schirmacher
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>. #}

{% extends 'experiment/view.html.twig' %}
{% block content %}
    {% for commit in commits|reverse %}
        {% include 'commit/commit.html.twig' %}
    {% endfor %}
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function () {
            var x = window.location.hash;
            if (x === '#drafts') {
                $('.tablinks')[4].click();
            }
        })
    </script>
{% endblock %}

templates/experiment/view/description.html.twig
{#  datenbank-physik
    Copyright (C) 2020  Christian Seybert, Jan-Philipp Rogge, Jacob Benz, Alexander Hartmann, Sarah Schirmacher
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>. #}

{% extends 'experiment/view.html.twig' %}
{% block content %}
    {% include 'image_slider.html.twig' %}
    <div class="content_container">
        {{ item.description|default(device.comment|default("Keine Beschreibung vorhanden"))|bbcode }}
        <hr>
        {{ item.comment|default(device.comment|default("Keine Bemerkung vorhanden"))|bbcode }}
    </div>
    <div class="inline_container">
        {% if item.preparationTime != null %}
            {% include 'sceletons/duration_clock.html.twig' with {'duration': item.preparationTime, 'title':'Vorbereitung'} %}
        {% endif %}
        {% if item.executionTime != null %}
            {% include 'sceletons/duration_clock.html.twig' with {'duration': item.executionTime, 'title':'Durchführung'} %}
        {% endif %}
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script>
        $('.slider').slick({
            infinite: false,
            speed: 300,
            slidesToShow: 1,
            centerMode: true,
            variableWidth: true,
            prevArrow: '<button type="button" class="slick-prev">{{ source('/icons/arrow_back-24px.svg')|escape('js') }}</button>',
            nextArrow: '<button type="button" class="slick-next">{{ source('/icons/arrow_forward-24px.svg')|escape('js') }}</button>'
        });
    </script>
{% endblock %}

templates/experiment/view/devices.html.twig
{#  datenbank-physik
    Copyright (C) 2020  Christian Seybert, Jan-Philipp Rogge, Jacob Benz, Alexander Hartmann, Sarah Schirmacher
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>. #}

{% extends 'experiment/view.html.twig' %}
{% block content %}
    {% if item.labels is empty %}
        <div class="warning">Diesem Experiment wurden keine Labels zugewiesen!</div>
    {% endif %}
    {% for label in item.labels %}
        {% include 'label/label.html.twig' %}
        {% if label.devices is empty %}
            <div class="warning">Es wurden keine passenden Geräte unter diesem Label gefunden!</div>
        {% else %}
            <div class="preview_card_container">
                {% for item in label.devices %}
                    {% include 'preview_card.html.twig' with {'title': item.name|default(''), 'description': item.description, 'id': item.id, type: 'device'} %}
                {% endfor %}
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}

templates/experiment/view/documents.html.twig
{#  datenbank-physik
    Copyright (C) 2020  Christian Seybert, Jan-Philipp Rogge, Jacob Benz, Alexander Hartmann, Sarah Schirmacher
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>. #}

{% extends 'experiment/view.html.twig' %}
{% block content %}
    <div class="inline_container">
        {% if item.documents is not empty %}
            {% for documents in item.documents %}
                {% if 'image' not in documents.typ and ('video/mp4' not in documents.typ or 'video/webm' not in documents.typ) and (is_granted("ROLE_SHOW_PRIVATE") or not documents.private) %}
                    <a class="card info_card" href="{{ vich_uploader_asset(documents, 'imageFile') }}" download="{{ documents.name }}">
                        <div>{{ documents.name|split('.')|first }}</div>
                        <div class="file_icon">.{{ documents.name|split('.')|last }}</div>
                        <div>{{ documents.comment }}</div>
                    </a>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}